<?php /* Smarty version Smarty-3.1.14, created on 2018-02-20 10:39:18
         compiled from "/Users/kosmos/Documents/sites/webassist.framework/wa-apps/contacts/templates/actions/contacts/ContactsAdd.html" */ ?>
<?php /*%%SmartyHeaderCode:12067465965a8bfad6ba22c1-68577119%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'f1e371d00bc905077bd2e596d15498b6c5470686' => 
    array (
      0 => '/Users/kosmos/Documents/sites/webassist.framework/wa-apps/contacts/templates/actions/contacts/ContactsAdd.html',
      1 => 1452519788,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '12067465965a8bfad6ba22c1-68577119',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'contactType' => 0,
    'wa_app_url' => 0,
    'contactFields' => 0,
    'contactFieldsOrder' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.14',
  'unifunc' => 'content_5a8bfad6cf3501_32651641',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5a8bfad6cf3501_32651641')) {function content_5a8bfad6cf3501_32651641($_smarty_tpl) {?><div class="block">
    <h1 class="wa-page-heading"></h1>
</div>

<div class="tab-content" id="c-info-container">
	<div class="block double-padded">
		<div class="fields">
			<div id="contact-info-block">
				<!-- Contents generated by JS later -->
			</div>
		</div>
		<div class="clear-left"></div>
	</div>
</div>

<div class="clear-left"></div>

<script type="text/javascript">
// contactEditor initialization code
$.wa.contactEditor.contact_id = null;
$.wa.contactEditor.current_user_id = null;
$.wa.contactEditor.contactType = '<?php echo $_smarty_tpl->tpl_vars['contactType']->value;?>
';
$.wa.contactEditor.wa_app_url = '<?php echo $_smarty_tpl->tpl_vars['wa_app_url']->value;?>
';

$.wa.contactEditor.initFactories(<?php echo json_encode($_smarty_tpl->tpl_vars['contactFields']->value);?>
, <?php echo json_encode($_smarty_tpl->tpl_vars['contactFieldsOrder']->value);?>
);
$.wa.contactEditor.initAllEditors();
$.wa.contactEditor.initContactInfoBlock('edit');
$(function() {
	window.setTimeout(function() { // voodoo magic... does not work without setTimeout() in IE8.
        <?php if ($_smarty_tpl->tpl_vars['contactType']->value=='person'){?>
            if ($.wa.contactEditor.fieldEditors.firstname) {
                $.wa.contactEditor.fieldEditors.firstname.domElement.find('.val:visible')[0].focus();
            }
        <?php }else{ ?>
            if ($.wa.contactEditor.fieldEditors.company) {
                $.wa.contactEditor.fieldEditors.company.domElement.find('.val:visible')[0].focus();
            }
        <?php }?>
	}, 1);
});
</script>

<?php }} ?>